extends:
  - "airbnb"
  - "prettier"
  - "prettier/react"
plugins:
  - "react"
  - "prettier"
env:
  es6: true
parserOptions:
  ecmaVersion: 2015
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: none
